language: node_js
script: npm test
sudo: false
dist: trusty
before_script:
  - psql -c 'create database pgpubsub_test;' -U postgres
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
services:
  - postgresql
matrix:
  include:
    - node_js: "6"
      addons:
        postgresql: "9.6"
    - node_js: "8"
      addons:
        postgresql: "9.2"
    - node_js: "8"
      addons:
        postgresql: "9.4"
    - node_js: "8"
      addons:
        postgresql: "9.6"
    - node_js: "8"
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - node_js: "9"
      addons:
        postgresql: "9.6"
    - node_js: "stable"
      addons:
        postgresql: "9.6"
