language: node_js
script: npm test
sudo: false
dist: trusty
before_script:
  - psql -c 'create database pgpubsub_test;' -U postgres -p ${PGPORT}
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
env:
  global:
  - PGPORT=5432
matrix:
  include:
    - node_js: "6"
      addons:
        postgresql: "9.6"
    - node_js: "8"
      addons:
        postgresql: "9.2"
    - node_js: "8"
      addons:
        postgresql: "9.4"
    - node_js: "8"
      addons:
        postgresql: "9.6"
    - node_js: "8"
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
      env:
        global:
        - PGPORT=5433
        - DATABASE_TEST_URL=postgres://postgres@localhost:${PGPORT}/pgpubsub_test
    - node_js: "9"
      addons:
        postgresql: "9.6"
    - node_js: "stable"
      addons:
        postgresql: "9.6"
