language: node_js
script: npm test
sudo: false
before_script:
  - psql -c 'create database pgpubsub_test;' -U postgres
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
matrix:
  include:
    - node_js: "4"
      addons:
        postgresql: "9.4"
    - node_js: "6"
      addons:
        postgresql: "9.6"
    - node_js: "6"
      addons:
        postgresql: "9.4"
    - node_js: "6"
      addons:
        postgresql: "9.1"
    - node_js: "7"
      addons:
        postgresql: "9.6"
    - node_js: "8"
      addons:
        postgresql: "9.6"
